dist: xenial

language: go

go:
  - 1.13.x

env: GO111MODULE=on

install: 
- go mod download
- go mod verify

# before_script:
#   - ...

script:
  - time make build
  - time make test
  - time make lint
